// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

class Person {
  let firstName: String
  let middleName: String?
  let lastName: String
  let age: Int32
  let otherFriend: Person?
  public static let typeID: Int32 = 1

  init(firstName: String, middleName: String?, lastName: String, age: Int32, otherFriend: Person) {
    self.firstName = firstName
    self.middleName = middleName
    self.lastName = lastName
    self.age = age
    self.otherFriend = otherFriend
  }

  init?(data: Data) {
    guard data.readTypeID() == Person.typeID else {
      return nil
    }

    var ptr = 24

    let firstNameSize = data.readSize(ofField: 0)
    guard let firstName = data.read(at: ptr, withLength: firstNameSize) else {
      return nil
    }
    ptr += firstNameSize
    self.firstName = firstName

    if data.readSize(ofField: 1) < 0 {
      self.middleName = nil
    } else {
      let middleNameSize = data.readSize(ofField: 1)
      guard let middleName = data.read(at: ptr, withLength: middleNameSize) else {
        return nil
      }
      ptr += middleNameSize
      self.middleName = middleName

    }

    let lastNameSize = data.readSize(ofField: 2)
    guard let lastName = data.read(at: ptr, withLength: lastNameSize) else {
      return nil
    }
    ptr += lastNameSize
    self.lastName = lastName

    let age: Int32 = data.readUnaligned(at: ptr)
    ptr += 4
    self.age = age

    let otherFriendSize = data.readSize(ofField: 4)
    if otherFriendSize < 0 {
      otherFriend = nil
    } else {
      otherFriend = Person(data: data.subdata(in: ptr..<ptr + otherFriendSize))
    }

  }

  func data() -> Data? {
    var data = Data()
    data.reserveCapacity(24)

    withUnsafeBytes(of: Person.typeID) {
      data.append(contentsOf: $0)
    }

    data.append([0], count: 20)

    data.write(size: firstName.lengthOfBytes(using: .utf8), ofField: 0)
    data.append(string: firstName)

    if let middleName = self.middleName {
      data.write(size: middleName.lengthOfBytes(using: .utf8), ofField: 1)
      data.append(string: middleName)

    } else {
      data.write(size: -1, ofField: 1)
    }

    data.write(size: lastName.lengthOfBytes(using: .utf8), ofField: 2)
    data.append(string: lastName)

    data.write(size: 4, ofField: 3)
    data.append(int: age.littleEndian)

    if let otherFriend = self.otherFriend, let otherFriendData = otherFriend.data() {
      data.append(otherFriendData)
      data.write(size: otherFriendData.count, ofField: 4)
    } else {
      data.write(size: -1, ofField: 4)
    }

    return data
  }
}
