#include "swift_generator.hxx"
#include "../../data_type/np_array.hxx"
#include "../../data_type/np_bool.hxx"
#include "../../data_type/np_double.hxx"
#include "../../data_type/np_int32.hxx"
#include "../../data_type/np_int8.hxx"
#include "../../data_type/np_map.hxx"
#include "../../data_type/np_optional.hxx"
#include "../../data_type/np_string.hxx"
#include "../../string_util/case_conv.hxx"
#include "swift_array_generator.hxx"
#include "swift_bool_generator.hxx"
#include "swift_double_generator.hxx"
#include "swift_int32_generator.hxx"
#include "swift_int8_generator.hxx"
#include "swift_map_generator.hxx"
#include "swift_message_generator.hxx"
#include "swift_optional_generator.hxx"
#include "swift_string_generator.hxx"
#include <filesystem>
#include <fstream>

const std::filesystem::path CODE_FILE_EXT(".np.swift");

SwiftGenerator::SwiftGenerator()
	: user_defined_message_type_generator(
		  std::make_shared<SwiftMessageGenerator>()),
	  data_type_generator_registry(
		  std::make_shared<DataTypeCodeGeneratorRegistry>()) {
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Bool::IDENTIFIER, std::make_shared<SwiftBoolGenerator>());
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Int8::IDENTIFIER, std::make_shared<SwiftInt8Generator>());
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Int32::IDENTIFIER, std::make_shared<SwiftInt32Generator>());
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Double::IDENTIFIER, std::make_shared<SwiftDoubleGenerator>());
	data_type_generator_registry->add_generator_for_type(
		NanoPack::String::IDENTIFIER, std::make_shared<SwiftStringGenerator>());
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Array::IDENTIFIER,
		std::make_shared<SwiftArrayGenerator>(data_type_generator_registry));
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Map::IDENTIFIER,
		std::make_shared<SwiftMapGenerator>(data_type_generator_registry));
	data_type_generator_registry->add_generator_for_type(
		NanoPack::Optional::IDENTIFIER,
		std::make_shared<SwiftOptionalGenerator>(data_type_generator_registry));
}

void SwiftGenerator::generate_for_schema(const MessageSchema &schema) {
	std::ofstream output_file_stream;
	CodeOutput code_output(output_file_stream, schema);
	std::filesystem::path output_path(schema.schema_path);
	output_path.replace_filename(snake_to_pascal(output_path.filename()))
		.replace_extension(CODE_FILE_EXT);

	output_file_stream.open(output_path);

	const size_t last_field_index = schema.declared_fields.size() - 1;

	// clang-format off
	code_output.stream()
	<< "// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND." << std::endl
	<< std::endl
	<< "import Foundation" << std::endl
	<< "import NanoPack" << std::endl
	<< std::endl
	<< "class " << schema.message_name << " {" << std::endl;
	// clang-format on

	for (const MessageField &field : schema.declared_fields) {
		std::shared_ptr<DataTypeCodeGenerator> generator =
			find_generator_for_field(field);
		if (generator != nullptr) {
			generator->generate_field_declaration(code_output, field);
		}
	}

	// clang-format off
	code_output.stream()
	<< "    public static let typeID: Int32 = " << schema.type_id << std::endl
	<< std::endl;
	// clang-format on

	code_output.stream() << "    init(";
	size_t i = 0;
	for (const MessageField &field : schema.declared_fields) {
		std::shared_ptr<DataTypeCodeGenerator> generator =
			find_generator_for_field(field);
		if (generator != nullptr) {
			generator->generate_constructor_parameter(code_output, field);
			if (i < last_field_index) {
				code_output.stream() << ", ";
			}
		}
		i++;
	}
	code_output.stream() << ") {" << std::endl;
	for (const MessageField &field : schema.declared_fields) {
		std::shared_ptr<DataTypeCodeGenerator> generator =
			find_generator_for_field(field);
		if (generator != nullptr) {
			generator->generate_constructor_field_initializer(code_output,
															  field);
			code_output.stream() << std::endl;
		}
	}
	code_output.stream() << "}" << std::endl << std::endl;

	// clang-format off
	code_output.stream()
	<< "    init?(data: Data) {" << std::endl
	<< "        guard data.readTypeID() == " << schema.message_name << ".typeID else {" << std::endl
	<< "            return nil" << std::endl
	<< "        }" << std::endl
	<< std::endl
	<< "        var ptr = " << (schema.declared_fields.size() + 1) * 4 << std::endl
	<< std::endl;
	// clang-format on

	for (const MessageField &field : schema.declared_fields) {
		std::shared_ptr<DataTypeCodeGenerator> generator =
			find_generator_for_field(field);
		if (generator != nullptr) {
			generator->generate_read_code(code_output, field);
			code_output.stream() << std::endl;
		}
	}

	// clang-format off
	code_output.stream()
	<< "    }" << std::endl // end init
	<< std::endl
	<< "    func data() -> Data? {" << std::endl
	<< "        var data = Data()" << std::endl
	<< "        data.reserveCapacity(" << (schema.declared_fields.size() + 1) * 4 << ")" << std::endl
	<< std::endl
	<< "        withUnsafeBytes(of: " << schema.message_name << ".typeID) {" << std::endl
	<< "            data.append(contentsOf: $0)" << std::endl
	<< "        }" << std::endl
	<< std::endl
	<< "        data.append([0], count: " << schema.declared_fields.size() * 4 << ")" << std::endl
	<< std::endl;
	// clang-format on

	for (const MessageField &field : schema.declared_fields) {
		std::shared_ptr<DataTypeCodeGenerator> generator =
			find_generator_for_field(field);
		if (generator != nullptr) {
			generator->generate_write_code(code_output, field);
			code_output.stream() << std::endl;
		}
	}

	// clang-format off
	code_output.stream()
	<< "        return data" << std::endl
	<< "    }" << std::endl // end func data()
	<< "}" << std::endl; // end extension
	// clang-format on

	output_file_stream.close();

	const std::string format_cmd =
		"swift-format --in-place " + output_path.string();
	system(format_cmd.c_str());
}

void SwiftGenerator::generate_message_factory(
	const std::vector<MessageSchema> &all_schemas,
	const std::filesystem::path &output_path) {

}


std::shared_ptr<DataTypeCodeGenerator>
SwiftGenerator::find_generator_for_field(const MessageField &field) {
	const auto generator =
		data_type_generator_registry->find_generator_for_type(field.type.get());
	if (generator == nullptr) {
		return user_defined_message_type_generator;
	}
	return generator;
}
