// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef PERSON_NP_HXX
#define PERSON_NP_HXX

#include <nanopack/nanobuf.hxx>
#include <optional>
#include <string>

struct Person {
private:
  static const int FIELD_COUNT = 4;

public:
  static const int32_t TYPE_ID = 1;

  std::string first_name;

  std::optional<std::string> middle_name;

  std::string last_name;

  int32_t age;

  Person();

  explicit Person(std::vector<uint8_t> &data);

  NanoBuf data();
};

#endif
