// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader } from "nanopack";
import { Widget } from "./widget.np.js";
import { Text } from "././text.np.js";

function makeWidget(bytes: Uint8Array) {
  const reader = new NanoBufReader(bytes);
  switch (reader.readTypeId()) {
    case 1:
      return Widget.fromReader(reader);
    case 2:
      return Text.fromReader(reader);
    default:
      return null;
  }
}

export { makeWidget };
