// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class Widget implements NanoPackMessage {
  public static TYPE_ID = 1;

  constructor(public id: number) {}

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Widget } | null {
    const reader = new NanoBufReader(bytes);
    if (reader.readTypeId() !== Widget.TYPE_ID) {
      return null;
    }
    let ptr = 8;

    const id = reader.readInt32(ptr);
    ptr += 4;

    return { bytesRead: ptr, result: new Widget(id) };
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    writer.writeTypeId(Widget.TYPE_ID);

    writer.appendInt32(this.id);
    writer.writeFieldSize(0, 4);

    return writer.bytes;
  }
}

export { Widget };
