// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

import { Text } from "./text.np.js";

class Widget implements NanoPackMessage {
  public static TYPE_ID = 1;

  constructor(public id: number) {}

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Widget } | null {
    const reader = new NanoBufReader(bytes);
    switch (reader.readTypeId()) {
      case 1:
        break;
      case 2:
        return Text.fromBytes(bytes);
      default:
        return null;
    }

    let ptr = 8;

    const id = reader.readInt32(ptr);
    ptr += 4;

    return { bytesRead: ptr, result: new Widget(id) };
  }

  public get typeId(): number {
    return 1;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    writer.writeTypeId(Widget.TYPE_ID);

    writer.appendInt32(this.id);
    writer.writeFieldSize(0, 4);

    return writer.bytes;
  }
}

export { Widget };
