// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef TEXT_NP_HXX
#define TEXT_NP_HXX

#include "widget.np.hxx"
#include <string>
#include <vector>

struct Text : Widget {
  static constexpr int32_t TYPE_ID = 2;

  std::string content;

  Text() = default;

  Text(int32_t id, std::string content);

  Text(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
